//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Globalization;
namespace Qif
{


    internal class Resources
    {
        public static readonly string BasicTransactionDisplay = "Date: {0}, Payee: {1}, Amount: {2}";
        public static readonly string InvalidBankTransaction = "Invalid bank transaction: {0}";
        public static readonly string InvalidBooleanFormat = "Invalid boolean format.";
        public static readonly string InvalidDateFormat = "Invalid date format.";
        public static readonly string InvalidDecimalFormat = "Invalid decimal format.";
        public static readonly string InvalidTransactionType = "Invalid transaction type.";
        public static readonly string InvestmentTransactionDisplay = "Date: {0}, Text: {1}, Amount: {2}";
        public static readonly string MemorizedTransactionDisplay = "Payee: {0}, Amount: {1}";
        public static readonly CultureInfo Culture = CultureInfo.CurrentUICulture;
    }
}
